version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - user-service
      - product-service
    extra_hosts:        # <--- fixed indentation here
      - "host.docker.internal:host-gateway"

  user-service:
    build: ./user-service
    container_name: user-service
    expose:
      - "5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - mongo

  product-service:
    build: ./product-service
    container_name: product-service
    expose:
      - "5001"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/productdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:


